server:
  port: 81

spring:
  application:
    name: cloud-consumer-order

  cloud:
    #consul的服务注册
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}