server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 101.42.230.55:8848         #Nacos????????
        password: nacos
        username: nacos
    sentinel:
      transport:
        dashboard: localhost:8080 #??Sentinel dashboard???????
        port: 8719 #??8719????????????8719????+1??,???????????
      web-context-unify: false #controller层的方法对service层的调用认为不是同一个根链路